ToDo/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using PracticeASP.NETCOREMVC.Models;


namespace ToDo
{
    public class ApplicationDbContext:DbContext
    {
        public DbSet<ToDoItem> items { get; set; }

        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
                : base(options)
            {

            }
        
    }
}

ToDo/Models/ErrorViewModel.cs
namespace PracticeASP.NETCOREMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ToDo/Models/ToDoItem.cs
using System.ComponentModel.DataAnnotations;

namespace PracticeASP.NETCOREMVC.Models
{
    public class ToDoItem
    {
        //GUID:Identificador global unico
        public Guid id { get; set; }
        public bool isDone { get; set; }


        [Required]
        public string title { get; set; }
        public DateTimeOffset? dueAt { get; set; }
        public DateTime? createdAt { get; set; }
}
    }

ToDo/Models/ToDoItems-Model-View.cs
using PracticeASP.NETCOREMVC.Models;

namespace ToDo.Models
{
    public class ToDoItems_Model_View
    {
        public ToDoItem[] toDoItems { get; set; }
    }
}

ToDo/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PracticeASP.NETCOREMVC.Models;
using System.Diagnostics;

namespace PracticeASP.NETCOREMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ToDo/Controllers/ToDoController.cs
using Microsoft.AspNetCore.Mvc;
using ToDo.Services;
using ToDo.Models;
using PracticeASP.NETCOREMVC.Models;



namespace PracticeASP.NETCOREMVC.Controllers
{
 
    public class ToDoController : Controller
    {
        private readonly IToDoItemService _todoItemService;
       

        public ToDoController(IToDoItemService toDoItemService)
        {
            _todoItemService = toDoItemService;
          

        }
        public async Task<IActionResult> Index()
        {
           
            var items = await _todoItemService.GetIncompleteItemsAsync();
            var model = new ToDoItems_Model_View
            {
                toDoItems = items
            };
            return View(model);
        }

       public async Task<IActionResult> Completed()
        {

            var items = await _todoItemService.GetCompleteItemsAsync();
            var model = new ToDoItems_Model_View
            {
                toDoItems = items
            };
            return View(model);
        }
            [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddItem(ToDoItem newItem)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }
            
            var successful = await _todoItemService.AddItemAsync(newItem);
            if (!successful)
            {
                return BadRequest("Could not add item.");
            }

            return RedirectToAction("Index");
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MarkDone(Guid id)
        {
            if (id == Guid.Empty)
            {
                return RedirectToAction("Index");
            }

            var successful = await _todoItemService.MarkDoneAsync(id);
            if (!successful)
            {
                return BadRequest("Could not mark item as done.");
            }

            return RedirectToAction("Index");
        }




    }
}

ToDo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ToDo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticeASP.NETCOREMVC.styles.css" asp-append-version="true" />
   
    
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ToDo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                      
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">ToDo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ToDo- <a asp-area="" asp-controller="ToDo" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
</body>
</html>

ToDo/Views/Todo/AddItemPartial.cshtml
@model ToDoItem
@{
    ViewData["Title"] = "AddItemPartial";
}

<form asp-action="AddItem" method="POST">
    <tr>
        
   <td> <label asp-for="title">Add a new item:</label></td>
    <td><input asp-for="title"> </td>
    </tr>
    <tr>
        
   <td><label asp-for="dueAt">dueAt</label></td>
 <td> <input asp-for="dueAt" type="date"> </td>
    </tr>
   
<button type="submit" class="btn btn-primary">Add</button>

     
</form>

ToDo/Views/Todo/Completed.cshtml
@using Humanizer
@model ToDo.Models.ToDoItems_Model_View

@{
    ViewData["Title"] = "Completed";
}

<div class="panel panel-default todo-panel">


  <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="ToDo">To-Do</a>
  </li>
  <li class="nav-item">
    <a class="nav-link"  asp-action="Completed" asp-controller="ToDo">Completed tasks </a>
  </li>
  
</ul>
<br />
  <div class="panel-heading">@ViewData["Title"]</div>
  <table class="table table-hover">
      <thead>
          <tr>
              
              <td>Item</td>
              <td>Registry Time</td>
              <td>Due</td>
              
          </tr>
      </thead>

      @foreach (var item in Model.toDoItems)
      {
          <tr>

              <td>@item.title</td>
              <td>@item.createdAt</td>
              <td>@item.dueAt.Humanize()</td>
        
             </tr>
          
             
      }
  </table>



  

ToDo/Views/Todo/Index.cshtml
@model ToDo.Models.ToDoItems_Model_View

@using Humanizer
@{
    ViewData["Title"] = "Manage your Task";
}


<div class="panel panel-default todo-panel">


  <ul class="nav nav-pills">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Index" asp-controller="ToDo">To-Do</a>
  </li>
  <li class="nav-item">
    <a class="nav-link"  asp-action="Completed" asp-controller="ToDo">Completed tasks </a>
  </li>
</ul>
  <div class="panel-heading">@ViewData["Title"]</div>
  <table class="table table-hover">
      <thead>
          <tr>
              
              <td>Item</td>
              <td>Due</td>
              <td>Registry time</td>
             
          </tr>
      </thead>

      @foreach (var item in Model.toDoItems)
      {
          
          
         
         <tr>
             <form asp-action="MarkDone" method="POST" asp-controller="ToDo">
             
             
              <td>@item.title</td>
              <td>@item.dueAt.Humanize()</td>
              <td>@item.createdAt</td>
              <td>
               <td>
               <button type="submit" class="btn btn-primary" >Completed</button>
               <input type="hidden" name="id" value="@item.id">
         </td>
        </form>
               
          </tr>
         
        
        

      }
  </table>
 </div>
  <div class="panel-footer add-item-form">
  @await Html.PartialAsync("AddItemPartial", new ToDoItem())
</div>